# Site settings - Customize these values for your personal website
title: "Bobby Saba - M.S." # Replace with your name
description: "Personal Academic Website - Research, Teaching, and More" # Brief site description
baseurl: "" # Leave empty for GitHub Pages main site, or "/repository-name" if using project pages
url: "https://bobbysaba.github.io" # Replace with your GitHub Pages URL

# Personal information - Update with your details
author:
  name: "Bobby Saba" # Your full name
  email: "robert.saba@ou.edu" # Your email
  bio: "PhD Student - School of Meteorology" # Short professional title
  location: "University of Oklahoma" # Your institution/location
  
# Social links - Add your social media handles (remove lines you don't want)
social:
  twitter: "bobbysabawx"
  linkedin: "bobbysabawx"
  github: "bobbysaba"
  # google_scholar: "your-scholar-id"
  orcid: "0009-0007-6492-8501"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for organizing content
collections:
  research:
    output: true
    permalink: /:collection/:name/
  teaching:
    output: true
    permalink: /:collection/:name/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research_item"
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "teaching_item"